export type cardType = 'technical' | 'social';
export type cardLabel = 'person' | 'activity' | 'requirement' | 'concept' | 'insight' | 'object';

export type fileExtension = 'txt' | 'png' | 'jpg' | 'jpeg' | 'json' | 'csv' | 'ipynb' | 'py' | 'js' | 'ts' | 'tsx' | 'jsx' | 'html' | 'css' | 'md' | 'pdf' | 'docx';

export type cardData = {
    label: string,
    type: cardType,
    title: string,
    attachmentIds?: string[];
    description?: string;
    createdAt?: string; // ISO string
    origin?: string; // file id
    reference?: string;
    autoGenerated?: boolean;
    relevant?: boolean;
    assignedTo?: string;
    [key: string]: unknown;
}

export type BlueprintComponent = {
    id: number;
    name: string;
    feedsInto: number[];
    description?: string;
    referenceCitation?: string;
    highBlockName: string;
    intermediateBlockName: string;
};

export type BlueprintIntermediate = {
    name: string;
    components: BlueprintComponent[];
};

export type BlueprintHighBlock = {
    name: string;
    intermediates: BlueprintIntermediate[];
};

export type BlueprintData = {
    fileName: string;
    paperTitle: string;
    year: number;
    highBlocks: BlueprintHighBlock[];
    components: BlueprintComponent[];
};

export type blueprintNodeData = {
    label: "blueprint";
    type: cardType;
    title: string;
    attachmentIds?: string[];
    description?: string;
    createdAt?: string;
    origin?: string;
    blueprint: BlueprintData;
};

export type blueprintComponentNodeData = {
    label: "blueprint_component";
    type: cardType;
    title: string;
    attachmentIds?: string[];
    codebaseFilePaths?: string[];
    manualCreated?: boolean;
    description?: string;
    createdAt?: string;
    origin?: string;
    blueprintComponent: BlueprintComponent;
    blueprintPaperTitle: string;
    blueprintFileName: string;
};

export type blueprintGroupNodeData = {
    label: "blueprint_group";
    type: cardType;
    title: string;
    attachmentIds?: string[];
    description?: string;
    createdAt?: string;
    origin?: string;
    blueprintGroupLevel: "paper" | "high" | "intermediate";
    blueprintPaperTitle: string;
    blueprintFileName: string;
};

export type llmCardData = {
    id: number,
    entity: string,
    title: string,
    description?: string,
    reference?: string
}

export type llmConnectionData = {
    source: number,
    target: number
}

// Frontend file record
export type filePendingUpload = {
    id: string;            
    name: string;
    ext: fileExtension;
    sizeBytes: number;
    mimeType: string;

    file: File;               

    previewText?: string;
};

// Backend file record
export type fileRecord = {
    id: string;
    docId: string;
    name: string;
    ext: fileExtension;
    sizeBytes: number;
    mimeType: string;
    createdAt: string; // ISO string

    sha256?: string;

    // Minio info
    storage?: { bucket: string; key: string };
};

export type nodeType = {
    id: string, // n123 or 123
    position: { x: number, y: number },
    type: string,
    data: cardData | blueprintNodeData | blueprintComponentNodeData | blueprintGroupNodeData,
    parentId?: string,
    extent?: "parent",
    style?: Record<string, string | number>,
    zIndex?: number
}

export type edgeType = {
    id: string,
    source: string,
    target: string,
    type?: string,
    label?: string,
    // optional metadata used by custom edges
    data?: any
}

export type GitHubEventType =
    | "commit"
    | "issue_opened"
    | "issue_closed"
    | "pr_opened"
    | "pr_closed"
    | "pr_merged";

export interface GitHubEvent {
    id: string;
    type: GitHubEventType;
    key: string;

    occurredAt: string; // ISO timestamp

    actor: string | null;
    title: string | null;
    url: string | null;

    issueNumber: number | null;
    prNumber: number | null;
    commitSha: string | null;
    branch: string | null;
    filesAffected: string[];

    payload: any;
}

export type LaneType = "codebase" | "knowledge" | "designStudy" | "blueprint";

export type Stage = {
    id: string;
    name: string;
    start: Date | string;
    end: Date | string;
};

export type SubStage = {
    id: string;
    lane: LaneType;
    start: Date | string;
    end: Date | string;
    name: string;
    stage: string;
};

export type DesignStudyEvent = {
    id: string;
    name: string;
    occurredAt: string; // ISO timestamp
    generatedBy?: "manual" | "llm";
}

export type CodebaseSubtrack = {
    id: string;
    name: string;
    filePaths: string[];
    collapsed: boolean;
    inactive: boolean;
};

export type BlueprintCodebaseLink = {
    id: string;
    blueprintEventId: string;
    codebaseSubtrackId: string;
    origin?: "manual" | "auto";
};

export type SystemScreenshotMarker = {
    id: string;
    occurredAt: string;
    imageDataUrl: string;
    imageWidth?: number;
    imageHeight?: number;
    zones?: SystemScreenshotZone[];
};

export type SystemScreenshotZone = {
    id: string;
    name: string;
    x: number;
    y: number;
    width: number;
    height: number;
    filePaths: string[];
    rationale?: string;
};

export type BlueprintEvent = {
    id: string;
    name: string;
    occurredAt: Date | string;
    componentNodeId?: string;
    paperDescription?: string;
    referenceCitation?: string;
    paperTitle?: string;
    blueprintFileName?: string;
};

export type TimelineState = {
    llmModel: string;
    stages: {
        byId: Record<string, Stage>;
        allIds: string[];
    };
    subStages: {
        byId: Record<string, SubStage>;
        allIds: string[];
    };
    designStudyEvents: {
        byId: Record<string, DesignStudyEvent>;
        allIds: string[];
    };
    blueprintEvents: {
        byId: Record<string, BlueprintEvent>;
        allIds: string[];
    };
    codebaseSubtracks: CodebaseSubtrack[];
    knowledgeSubtracks: CodebaseSubtrack[];
    knowledgePillTrackAssignments: Record<string, string | null>;
    blueprintCodebaseLinks: BlueprintCodebaseLink[];
    systemScreenshotMarkers: SystemScreenshotMarker[];
    participants: ProjectParticipant[];
    hoveredCodebaseFilePath: string | null;
    highlightedCodebaseFilePaths: string[];
    highlightedKnowledgeNodeIds: string[];
    hoveredBlueprintComponentNodeId: string | null;
    defaultStages: string[];
    timelineStartEnd: {
        start: string;
        end: string;
    };
};

export type TimelineStatePayload = {
    llmModel?: string;
    stages: Stage[];
    subStages: SubStage[];
    designStudyEvents: DesignStudyEvent[];
    blueprintEvents: BlueprintEvent[];
    codebaseSubtracks: CodebaseSubtrack[];
    knowledgeSubtracks?: CodebaseSubtrack[];
    knowledgePillTrackAssignments?: Record<string, string | null>;
    blueprintCodebaseLinks: BlueprintCodebaseLink[];
    systemScreenshotMarkers?: SystemScreenshotMarker[];
    participants: ProjectParticipant[];
    defaultStages: string[];
    timelineStartEnd: {
        start: string;
        end: string;
    };
};

export type ProjectParticipant = {
    id: string;
    name: string;
    role: string;
};
