import { memo, useCallback, useEffect, useMemo, useState, useSyncExternalStore } from 'react';

import classes from './Card.module.css';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faRepeat, faWandMagicSparkles, faXmark } from '@fortawesome/free-solid-svg-icons';

import { Position, Handle } from '@xyflow/react';
import { AttachFileZone } from '@/components/files/AttachFileZone';
import { useSelector } from 'react-redux';
import type { fileRecord, nodeType } from '@/config/types';
import type { RootState } from '@/store';
import { FileSlot } from '@/components/files/FileSlot';
import { CardPreviewDockContext } from '@/components/cards/cardPreviewDock';
import FileModal from '@/components/files/FileModal';
import { FileDocumentView } from '@/components/files/FileDocumentView';
import { CARD_LABEL_COLORS, CARD_LABEL_ICONS, CARD_LABELS, normalizeCardLabel } from '@/components/cards/cardVisuals';
import { toLocalDateTimeInputValue } from '@/utils/dateTime';
import {
    isAssetHighlighted,
    isKnowledgeHighlighted,
    subscribe as subscribeHighlight,
} from '@/store/canvasHighlightStore';

/** Must match `transition: transform 0.8s` on `.flipCardInner`. */
const FLIP_MS = 800;

function LabelIcon({ label }: { label: string }) {
    const icon = CARD_LABEL_ICONS[normalizeCardLabel(label)];
    if (!icon) return null;
    return (
        <FontAwesomeIcon className={classes.flipIcon} icon={icon} />
    )
}

export type CardProps = {
    id?: string;
    data: {
        label: string;
        type: string;
        title: string;
        description?: string;
        attachmentIds?: string[];
        createdAt?: string;
        origin?: string;
        reference?: string;
        autoGenerated?: boolean;
        relevant?: boolean;
        assignedTo?: string;
    };
    onAttachFile?: (nodeId: string, file: File) => void;
    onDetachFile?: (nodeId: string, fileId: string) => void;
    onDataPropertyChange?: (nodeProps: nodeType, value: unknown, propertyName: string) => void;
    onDeleteNode?: (nodeId: string) => void;
    participantOptions?: string[];
    selected?: boolean;
    dragging?: boolean;
    [key: string]: unknown;
};

function CardImpl(props: CardProps) {
    // Which face is showing at rest, and whether a flip is in flight. Splitting the two is what lets
    // a resting card drop its 3D context and its hidden face: `face` decides what is mounted,
    // `flipping` alone pays for the animation. See the flip block in `Card.module.css`.
    const [face, setFace] = useState<"front" | "back">("front");
    // The host the open file preview panel portals into — see `CardPreviewDock`. Held as state, not
    // a ref, because the panel is a React subtree: it can only be created once the element exists,
    // and a ref assignment would not re-render to say so.
    const [previewDock, setPreviewDock] = useState<HTMLDivElement | null>(null);
    // Whether the source document this card was extracted from is open beside the card. Kept here
    // rather than in the meta section that opens it, because that section lives on the back face and
    // is unmounted the moment the card is flipped — the panel has to outlive the face.
    const [sourceOpen, setSourceOpen] = useState(false);
    const [flipping, setFlipping] = useState(false);

    const flipTo = useCallback((next: "front" | "back") => {
        setFace(next);
        setFlipping(true);
    }, []);

    const handleFlipTransitionEnd = useCallback((event: React.TransitionEvent<HTMLDivElement>) => {
        // The inner wrapper's own transform, not a transition bubbling up from a descendant.
        if (event.target !== event.currentTarget) return;
        if (event.propertyName !== "transform") return;
        setFlipping(false);
    }, []);

    // `transitionend` is not guaranteed — a backgrounded tab or a reduced-motion override can swallow
    // it — and a stuck `flipping` would keep both faces and the 3D context alive for the life of the
    // card, which is the cost this split exists to avoid.
    useEffect(() => {
        if (!flipping) return;
        const timer = window.setTimeout(() => setFlipping(false), FLIP_MS + 150);
        return () => window.clearTimeout(timer);
    }, [flipping]);

    const showFront = face === "front" || flipping;
    const showBack = face === "back" || flipping;

    // Highlight arrives as a boolean from an external store rather than as an injected `node.style`,
    // so hovering a timeline pill or an asset re-renders the two cards whose boolean flipped instead of
    // rebuilding every node object and re-running the whole derivation chain. See
    // `store/canvasHighlightStore.ts`.
    const knowledgeHighlighted = useSyncExternalStore(
        subscribeHighlight,
        () => isKnowledgeHighlighted(props.id),
    );
    const assetHighlighted = useSyncExternalStore(
        subscribeHighlight,
        () => isAssetHighlighted(props.data?.attachmentIds),
    );

    const attachmentIds = props.data?.attachmentIds;
    // A card holds at most one file. Projects saved before that rule can still carry several, so
    // the first one is shown rather than dropped: detaching it reveals the next, and the card
    // converges on a single attachment without losing anything behind the user's back.
    //
    // Selects the file itself rather than the whole `files.byId` map: subscribing to the map made
    // every card on the canvas re-render whenever any file anywhere changed. The record is a stable
    // reference until it is actually replaced, so the default identity comparison holds.
    const attachedFile = useSelector<RootState, fileRecord | null>((state) => {
        if (!Array.isArray(attachmentIds)) return null;
        for (const fileId of attachmentIds) {
            const file = state.files.byId[fileId];
            if (file) return file;
        }
        return null;
    });

    const originFile = useSelector<RootState, fileRecord | null>((state) => {
        const origin = props.data?.origin;
        if (typeof origin !== "string" || origin.trim() === "") return null;
        return state.files.byId[origin] ?? null;
    });

    const dropZoneCSS = useMemo<React.CSSProperties>(() => ({
        borderRadius: "8",
        textAlign: "center",
        background: "transparent",
        transition: "background 0.2s ease",
    }), []);

    // Stable, or `AttachFileZone`'s memo could never hold.
    const nodeId = props.id;
    const onAttachFile = props.onAttachFile;
    const handleFileSelected = useCallback((file: File) => {
        if (!nodeId) return;
        onAttachFile?.(nodeId, file);
    }, [nodeId, onAttachFile]);

    const getCleanNodeProps = () => {
        const cleanProps = { ...props };
        delete cleanProps.onAttachFile;
        delete cleanProps.onDetachFile;
        delete cleanProps.onDataPropertyChange;
        delete cleanProps.onDeleteNode;
        delete cleanProps.participantOptions;
        return cleanProps as unknown as nodeType;
    };

    const [isEditingLabel, setIsEditingLabel] = useState(false);
    const [isEditingTitle, setIsEditingTitle] = useState(false);
    const [isEditingDescription, setIsEditingDescription] = useState(false);
    const [isEditingCreatedAt, setIsEditingCreatedAt] = useState(false);
    const [draftCreatedAt, setDraftCreatedAt] = useState("");

    const [draftTitle, setDraftTitle] = useState(props.data.title);
    const [draftDescription, setDraftDescription] = useState(props.data.description ?? '');
    const normalizedLabel = normalizeCardLabel(props.data.label);
    const isTaskOrRequirement = normalizedLabel === "requirement";
    const participantOptions = Array.isArray(props.participantOptions) ? props.participantOptions : [];
    const assignedTo = typeof props.data.assignedTo === "string" ? props.data.assignedTo : "";
    const reference = typeof props.data.reference === "string" ? props.data.reference.trim() : "";
    const originFileName = originFile?.name ?? "";
    // Two different questions, deliberately not one flag.
    //
    // `isModelDerived` is "did a model write this card": `autoGenerated` alone, which
    // `llmCardsToNodes` stamps on every card either LLM path produces and nothing else sets. It is
    // what the badge shows and what the sidebar's provenance filter hides, so it has to mean exactly
    // that — a card the user dragged in from a file carries `origin` too, and is not model-derived.
    //
    // `hasSourceMetadata` is the weaker "is there a source worth citing on the back", which is true
    // for the hand-dropped card as well.
    const isModelDerived = props.data.autoGenerated === true;
    // The complement, stated positively. A card with no `autoGenerated` flag was put here by a
    // person -- typed as a note, dropped as a file, or drawn with the card tool -- and that is the
    // only thing on this canvas that is the researcher's own doing rather than the model's.
    const isAuthored = !isModelDerived;
    const hasSourceMetadata = Boolean(props.data.autoGenerated || props.data.origin || reference);
    const isRelevant = props.data.relevant !== false;
    const createdAtText = (() => {
        if (!props.data.createdAt) return "Set timestamp";
        const parsed = new Date(props.data.createdAt);
        if (Number.isNaN(parsed.getTime())) return "Set timestamp";
        return parsed.toLocaleString();
    })();

    // Only activities: their timestamp is what places them on the canvas time axis, so it is the
    // one that has to be correctable. Every other card inherits the moment it was created.
    const isActivity = normalizedLabel === "activity";

    const openCreatedAtEditor = () => {
        const parsed = props.data.createdAt ? new Date(props.data.createdAt) : new Date();
        setDraftCreatedAt(toLocalDateTimeInputValue(Number.isNaN(parsed.getTime()) ? new Date() : parsed));
        setIsEditingCreatedAt(true);
    };

    const commitCreatedAt = () => {
        setIsEditingCreatedAt(false);
        if (!draftCreatedAt) return;
        // `datetime-local` carries no zone, and a date-TIME string without one is parsed as local
        // time — the same convention `toLocalDateTimeInputValue` writes, so this round-trips.
        const parsed = new Date(draftCreatedAt);
        if (Number.isNaN(parsed.getTime())) return;
        props.onDataPropertyChange?.(getCleanNodeProps(), parsed.toISOString(), "createdAt");
    };

    return (
        <div
            className={[
                classes.card,
                flipping ? classes.flipCard3d : "",
                !isRelevant ? classes.cardNotRelevant : "",
                isModelDerived ? classes.modelDerived : "",
                isAuthored ? classes.authored : "",
                knowledgeHighlighted ? classes.knowledgeHighlight : "",
                assetHighlighted ? classes.assetHighlight : "",
            ].filter(Boolean).join(" ")}
        >

            <CardPreviewDockContext value={previewDock}>
            <div
                className={[
                    classes.flipCardInner,
                    flipping ? classes.flipCardInner3d : "",
                    face === "back" ? classes.flipAnimation : "",
                ].filter(Boolean).join(" ")}
                onTransitionEnd={handleFlipTransitionEnd}
            >

                {showFront ? (
                <div className={`${classes.flipCardFront} ${flipping ? classes.flipCardHideBackface : ""} ${props.data.type == "social" ? classes.socialCard : classes.techCard}`}>
                    <div className={classes.header}>
                        <div className={classes.headerLeft}>
                            {isEditingLabel ? (
                                <select
                                    value={normalizedLabel}
                                    autoFocus
                                    onChange={(e) => {
                                        const newLabel = e.target.value;
                                        props.onDataPropertyChange?.(getCleanNodeProps(), newLabel, "label");
                                        setIsEditingLabel(false);
                                    }}
                                    onBlur={() => setIsEditingLabel(false)}
                                >
                                    {CARD_LABELS.map(label => (
                                        <option key={label} value={label}>
                                            {label[0].toUpperCase() + label.slice(1)}
                                        </option>
                                    ))}
                                </select>
                            ) : (
                                <p
                                    className={classes.label}
                                    onClick={() => setIsEditingLabel(true)}
                                >
                                    {normalizedLabel[0].toUpperCase() + normalizedLabel.slice(1)}
                                </p>
                            )}

                            {isModelDerived ? (
                                <span
                                    className={classes.modelDerivedBadge}
                                    title="Proposed by the model from a source document. Flip the card to read the excerpt it came from."
                                >
                                    <FontAwesomeIcon icon={faWandMagicSparkles} />
                                    AI
                                </span>
                            ) : null}
                        </div>

                        <div className={classes.headerRight}>
                            <button
                                type="button"
                                className={`${classes.relevantToggle} ${isRelevant ? classes.relevantToggleOn : classes.relevantToggleOff}`}
                                onClick={(event) => {
                                    event.stopPropagation();
                                    props.onDataPropertyChange?.(getCleanNodeProps(), !isRelevant, "relevant");
                                }}
                            >
                                {isRelevant ? "Relevant" : "Not Relevant"}
                            </button>
                            <FontAwesomeIcon className={classes.flipIcon} icon={faRepeat} onClick={() => flipTo("back")} />
                            {props.id ? (
                                <button
                                    type="button"
                                    className={classes.headerDeleteButton}
                                    title="Delete card"
                                    onClick={(event) => {
                                        event.stopPropagation();
                                        if (!props.id) return;
                                        props.onDeleteNode?.(props.id);
                                    }}
                                >
                                    <FontAwesomeIcon icon={faXmark} />
                                </button>
                            ) : null}
                        </div>
                    </div>
                    <div className={classes.attachments}>
                        <div
                            className={classes.labelIcon}
                            style={{
                                backgroundColor: CARD_LABEL_COLORS[normalizedLabel],
                                top: "-10px",
                                left: "-3px",
                            }}
                        >
                            <LabelIcon
                                label={normalizedLabel}
                            />
                        </div>

                        <FileSlot
                            file={attachedFile}
                            onRemoveFile={(fileId) => {
                                if (!props.id) return;
                                props.onDetachFile?.(props.id, fileId);
                            }}
                        >
                            <AttachFileZone
                                onFileSelected={handleFileSelected}
                                dropZoneCSS={dropZoneCSS}
                                loading={false}
                                accept='.txt, .png, .jpg, .jpeg, .json, .csv, .ipynb, .py, .js, .ts, .tsx, .jsx, .html, .css, .md, .docx, .pdf, .mp4, .webm, .mov, .m4v, .ogg, .ogv, .avi'
                            />
                        </FileSlot>
                    </div>
                    <div className={classes.title}>
                        {isEditingTitle ? (
                            <textarea
                                className={`${classes.fieldTextEditor} nodrag`}
                                value={draftTitle}
                                autoFocus
                                rows={1}
                                onChange={(e) => setDraftTitle(e.target.value)}
                                onBlur={() => {
                                    props.onDataPropertyChange?.(getCleanNodeProps(), draftTitle.trim(), "title");
                                    setIsEditingTitle(false);
                                }}
                                onKeyDown={(e) => {
                                    if (e.key === "Enter" && !e.shiftKey) {
                                        e.preventDefault();
                                        props.onDataPropertyChange?.(getCleanNodeProps(), draftTitle.trim(), "title");
                                        setIsEditingTitle(false);
                                    }
                                    if (e.key === "Escape") {
                                        setDraftTitle(props.data.title);
                                        setIsEditingTitle(false);
                                    }
                                }}
                            />
                        ) : (
                            <p
                                className={classes.title}
                                onClick={() => {
                                    setDraftTitle(props.data.title);
                                    setIsEditingTitle(true);
                                }}
                            >
                                {props.data.title || "Untitled"}
                            </p>
                        )}
                    </div>
                    {isTaskOrRequirement ? (
                        <p className={classes.assignedText}>Assigned to: {assignedTo || "Unassigned"}</p>
                    ) : null}

                </div>
                ) : null}

                {showBack ? (
                <div className={`${classes.flipCardBack} ${flipping ? classes.flipCardHideBackface : ""} ${props.data.type == "social" ? classes.socialCardBack : classes.techCardBack}`}>
                    <div className={classes.header}>
                        <p>{`${normalizedLabel[0].toUpperCase()}${normalizedLabel.slice(1)}`}</p>
                        <FontAwesomeIcon className={classes.flipIcon} icon={faRepeat} onClick={() => flipTo("front")} />
                    </div>
                    <div className={classes.backBody}>
                        <div
                            className={classes.labelIcon}
                            style={{
                                backgroundColor: CARD_LABEL_COLORS[normalizedLabel],
                                top: "-4px",
                                left: "-5px",
                            }}
                        >
                            <LabelIcon
                                label={normalizedLabel}
                            />
                        </div>

                        {/* <p className={classes.backText}>{props.data.description}</p> */}
                        {isEditingDescription ? (
                            <textarea
                                className={`${classes.fieldTextEditor} nodrag`}
                                style={{fontSize: "var(--font-size-xs)", color: "white"}}
                                value={draftDescription}
                                autoFocus
                                rows={1}
                                onChange={(e) => {
                                    setDraftDescription(e.target.value);
                                }}
                                onBlur={() => {
                                    props.onDataPropertyChange?.(getCleanNodeProps(), draftDescription.trim(), "description");
                                    setIsEditingDescription(false);
                                }}
                                onKeyDown={(e) => {
                                    if (e.key === "Enter" && !e.shiftKey) {
                                        e.preventDefault();
                                        props.onDataPropertyChange?.(getCleanNodeProps(), draftDescription.trim(), "description");
                                        setIsEditingDescription(false);
                                    }
                                    if (e.key === "Escape") {
                                        if(props.data.description == '' || !props.data.description)
                                            setDraftDescription("Empty description.");
                                        else
                                            setDraftDescription(props.data.description);
                                        setIsEditingDescription(false);
                                    }
                                }}
                            />
                        ) : (
                            <p
                                className={classes.backText}
                                onClick={() => {
                                    if(props.data.description == '' || !props.data.description)
                                        setDraftDescription("Empty description.");
                                    else
                                        setDraftDescription(props.data.description);
                                    setIsEditingDescription(true);
                                }}
                            >
                                {props.data.description || "Empty description."}
                            </p>
                        )}

                        {isActivity ? (
                            isEditingCreatedAt ? (
                                <input
                                    type="datetime-local"
                                    className={`${classes.createdAtEditor} nodrag`}
                                    value={draftCreatedAt}
                                    autoFocus
                                    onChange={(event) => setDraftCreatedAt(event.target.value)}
                                    onBlur={commitCreatedAt}
                                    onKeyDown={(event) => {
                                        if (event.key === "Enter") {
                                            event.preventDefault();
                                            commitCreatedAt();
                                        }
                                        if (event.key === "Escape") {
                                            setIsEditingCreatedAt(false);
                                        }
                                    }}
                                />
                            ) : (
                                <p
                                    className={`${classes.createdAtText} ${classes.createdAtEditable}`}
                                    title="Edit activity timestamp"
                                    onClick={openCreatedAtEditor}
                                >
                                    {createdAtText}
                                </p>
                            )
                        ) : (
                            <p className={classes.createdAtText}>{createdAtText}</p>
                        )}

                        {hasSourceMetadata ? (
                            <div className={classes.metaSection}>
                                {reference ? (
                                    originFile ? (
                                        // The excerpt is a claim about a document; clicking it should
                                        // take you to where the document says it, not merely open the
                                        // file and leave you to search. Opens the source docked beside
                                        // the card and scrolls it to the passage.
                                        <button
                                            type="button"
                                            className={`${classes.metaReferenceButton} nodrag`}
                                            title="Show this passage in the source document"
                                            onClick={(event) => {
                                                event.stopPropagation();
                                                setSourceOpen(true);
                                            }}
                                        >
                                            <span className={classes.metaLabel}>Reference:</span> {reference}
                                        </button>
                                    ) : (
                                        <p className={classes.metaText}>
                                            <span className={classes.metaLabel}>Reference:</span> {reference}
                                        </p>
                                    )
                                ) : null}
                                {originFileName ? (
                                    originFile ? (
                                        // Checking a model-derived card should cost a click, not an
                                        // investigation: this opens the document the excerpt above
                                        // was taken from, docked beside the card, so the claim and
                                        // its evidence are on screen together.
                                        <button
                                            type="button"
                                            className={`${classes.metaOpenSource} nodrag`}
                                            title={`Open ${originFileName} beside this card`}
                                            onClick={(event) => {
                                                event.stopPropagation();
                                                setSourceOpen(true);
                                            }}
                                        >
                                            <span className={classes.metaLabel}>Source file:</span>
                                            <span className={classes.metaOpenSourceName}>{originFileName}</span>
                                        </button>
                                    ) : (
                                        <p className={classes.metaText}>
                                            <span className={classes.metaLabel}>Source file:</span> {originFileName}
                                        </p>
                                    )
                                ) : null}
                            </div>
                        ) : null}

                        {isTaskOrRequirement ? (
                            <div className={classes.assignmentSection}>
                                <label className={classes.assignmentLabel}>
                                    Assigned participant
                                    <select
                                        className={classes.assignmentSelect}
                                        value={assignedTo}
                                        onChange={(event) => {
                                            props.onDataPropertyChange?.(getCleanNodeProps(), event.target.value, "assignedTo");
                                        }}
                                    >
                                        <option value="">Unassigned</option>
                                        {participantOptions.map((name) => (
                                            <option key={name} value={name}>
                                                {name}
                                            </option>
                                        ))}
                                    </select>
                                </label>
                            </div>
                        ) : null}
                    </div>
                </div>
                ) : null}

            </div>

            {originFile ? (
                <FileModal
                    open={sourceOpen}
                    onClose={() => setSourceOpen(false)}
                    title={originFile.name}
                >
                    <FileDocumentView file={originFile} highlight={reference || undefined} />
                </FileModal>
            ) : null}
            </CardPreviewDockContext>

            {/* The column the open document panels portal into, pinned beside the card's right
                edge and out of flow, so it takes no space until something opens. `.card` contains
                layout and style but deliberately not paint, so the panels draw outside it. */}
            <div ref={setPreviewDock} className={classes.previewDock} />

            {
                props.id != undefined
                    ?
                    <>
                        <Handle type="target" position={Position.Left} />
                        <Handle type="source" position={Position.Right} />
                    </>
                    :
                    null
            }

        </div>
    );
}

function areEqualCardProps(prev: CardProps, next: CardProps) {
    return (
        prev.id === next.id &&
        prev.data === next.data &&
        prev.selected === next.selected &&
        prev.dragging === next.dragging &&
        prev.onAttachFile === next.onAttachFile &&
        prev.onDetachFile === next.onDetachFile &&
        prev.onDataPropertyChange === next.onDataPropertyChange &&
        prev.onDeleteNode === next.onDeleteNode &&
        prev.participantOptions === next.participantOptions
    );
}

export const Card = memo(CardImpl, areEqualCardProps);
