import { useCallback, useEffect, useRef } from "react";

import { parseFile } from "@/func/FileParser";
import { llmCardsToNodes, requestCardsLLM } from "@/func/LLMRequest";
import type { LlmProjectSettingsContext } from "@/func/LLMRequest";
import { compareCardsSimilarity, createFile } from "@/api/stateApi";
import {
    decideSimilarityEdges,
    SIMILARITY_TUNING,
    type IterationEvidence,
} from "@/pages/projectEditor/similarityDecision";
import {
    canAutoLink,
    connectionKindFromEdge,
    isEdgeActive,
    type ConnectionKind,
} from "@/pages/projectEditor/graphSemantics";
import { addNode, attachFileIdToNode, addNodes, connectEdges } from "@/store/flowSlice";
import { upsertFile } from "@/store/filesSlice";
import { relationLabelFor } from "@/utils/relationships";

import type { AppDispatch } from "@/store";
import type { edgeType, filePendingUpload, llmCardData, llmConnectionData, nodeType } from "@/config/types";

type Args = {
    projectId: string;
    dispatch: AppDispatch;
    nodes: nodeType[];
    edges: edgeType[];
    projectSettings: LlmProjectSettingsContext;
    actionTimestamp?: string | null;
    setLoading: (value: boolean) => void;
    /** Surfaced to the user in place of the old blocking `alert`. */
    onExtractionError?: (message: string) => void;
};

/**
 * The relation a dropped file's card gets to the activity it landed on. Chosen once per drop and
 * applied to every file in it, so a batch never ends up half `generated by` and half something else.
 */
export type CanvasDropConnection = {
    label: string;
    /** Set for the two semantic relations; left out for the pair's own default label. */
    kind?: Exclude<ConnectionKind, "regular">;
};

const KNOWN_CARD_LABELS = new Set(["person", "activity", "requirement", "concept", "insight", "object"]);
const REFERENCED_BY_LABEL = "referenced by";
const ITERATION_OF_LABEL = "iteration of";
const DEBUG_SIMILARITY_SCORES = String(import.meta.env.VITE_DEBUG_SIMILARITY_SCORES ?? "").toLowerCase() === "true";
const VIDEO_EXTENSIONS = new Set(["mp4", "webm", "mov", "m4v", "ogg", "ogv", "avi"]);

/**
 * Automatic edges already attached to each card, both ends counted.
 *
 * This is what stops one card becoming a hub. A long, topic-summarising title sits near the centre
 * of a project's subject matter and therefore wins "most similar" against cards that have nothing
 * to do with each other — and because salience weights degree, such a hub does not just clutter the
 * canvas, it hijacks which cards get promoted when the canvas is abstracted.
 */
function countAutoLinkDegree(edges: edgeType[]): Map<string, number> {
    const degree = new Map<string, number>();
    for (const edge of edges) {
        if (!isEdgeActive(edge)) continue;
        if (connectionKindFromEdge(edge) === "regular") continue;
        degree.set(edge.source, (degree.get(edge.source) ?? 0) + 1);
        degree.set(edge.target, (degree.get(edge.target) ?? 0) + 1);
    }
    return degree;
}

function normalizeArtifactEntity(entity: string | undefined): string {
    const normalized = String(entity ?? "").trim().toLowerCase();
    if (normalized === "task") return "requirement";
    if (KNOWN_CARD_LABELS.has(normalized)) return normalized;
    return "object";
}

function typeFromLabel(label: string): "technical" | "social" {
    return label === "requirement" || label === "insight" ? "technical" : "social";
}

function titleFromFilename(filename: string): string {
    const withoutExt = filename.replace(/\.[^/.]+$/, "").trim();
    return withoutExt || "Untitled";
}

function extensionFromName(filename: string): string {
    if (!filename.includes(".")) return "";
    return filename.split(".").pop()?.toLowerCase() ?? "";
}

function isVideoMimeType(mimeType: string | undefined): boolean {
    return typeof mimeType === "string" && mimeType.toLowerCase().startsWith("video/");
}

function isVideoFile(file: File): boolean {
    return isVideoMimeType(file.type) || VIDEO_EXTENSIONS.has(extensionFromName(file.name));
}

function isVideoPendingUpload(file: filePendingUpload): boolean {
    return isVideoMimeType(file.mimeType) || VIDEO_EXTENSIONS.has(String(file.ext ?? "").toLowerCase());
}

export function useFileAttachmentProcessing({
    projectId,
    dispatch,
    nodes,
    edges,
    projectSettings,
    actionTimestamp = null,
    setLoading,
    onExtractionError,
}: Args) {
    const nodesRef = useRef(nodes);
    const edgesRef = useRef(edges);
    // Every in-flight drop, so switching projects mid-drop cannot let an upload or extraction
    // dispatch its results into a different document's store. Concurrent drops are kept
    // independent: starting one must never cancel another that is still running.
    const inFlightRef = useRef<Set<AbortController>>(new Set());

    useEffect(() => {
        nodesRef.current = nodes;
    }, [nodes]);

    useEffect(() => {
        edgesRef.current = edges;
    }, [edges]);

    useEffect(() => {
        const controllers = inFlightRef.current;
        return () => {
            for (const controller of controllers) controller.abort();
            controllers.clear();
        };
    }, [projectId]);

    const resolveActionTimestamp = useCallback(() => {
        if (actionTimestamp) {
            const parsed = new Date(actionTimestamp);
            if (!Number.isNaN(parsed.getTime())) return parsed.toISOString();
        }
        return new Date().toISOString();
    }, [actionTimestamp]);

    /**
     * Attach a file to an activity card and let the LLM turn it into cards.
     *
     * The file's timestamp is the current timeline action timestamp — there is no prompt for it.
     * An activity's own timestamp is editable on the back of its card, which is the one place that
     * decides where the tree sits on the time axis, so asking again per file was a modal in the way
     * of every attachment.
     */
    const processFile = useCallback(async (
        file: File,
        rootActivityNodeId: string,
        dropPosition?: { x: number; y: number },
    ) => {
        setLoading(true);
        const controller = new AbortController();
        inFlightRef.current.add(controller);
        const { signal } = controller;

        try {
            const data: filePendingUpload = await parseFile(file);
            const chosenCreatedAt = resolveActionTimestamp();

            // The extraction call needs only the parsed file, never the upload result, so the two
            // run concurrently. For pdf/docx this also overlaps the docling conversion with the
            // upload, since that round trip happens inside requestCardsLLM.
            const isVideo = isVideoPendingUpload(data);
            const uploadPromise = createFile(projectId, data, chosenCreatedAt, signal);
            const llmPromise = isVideo ? null : requestCardsLLM(data, projectSettings, signal);
            // Attached up front so a failure on one leg is never an unhandled rejection while the
            // other is still in flight.
            uploadPromise.catch(() => { });
            llmPromise?.catch(() => { });

            const uploaded = await uploadPromise;
            const {
                fileId,
                createdAt: persistedCreatedAt,
                sha256,
                bucket,
                key,
            } = uploaded;
            const parsedPersistedCreatedAt = new Date(persistedCreatedAt);
            const resolvedCreatedAt = Number.isNaN(parsedPersistedCreatedAt.getTime())
                ? chosenCreatedAt
                : parsedPersistedCreatedAt.toISOString();
            const { name, mimeType, sizeBytes, ext } = data;

            dispatch(upsertFile({
                id: fileId,
                docId: projectId,
                name,
                mimeType,
                sizeBytes,
                ext,
                createdAt: resolvedCreatedAt,
                sha256,
                storage: { bucket, key },
            }));

            // Attach as soon as upload metadata is available, independent of LLM success.
            dispatch(attachFileIdToNode({
                nodeId: rootActivityNodeId,
                fileId,
                editAt: chosenCreatedAt,
            }));

            if (!llmPromise) {
                return;
            }

            let response: { cards: llmCardData[]; connections: llmConnectionData[] } | null = null;
            try {
                response = await llmPromise;
            } catch (error) {
                if (signal.aborted) return;
                console.error("LLM processing failed for attached file.", error);
                onExtractionError?.(error instanceof Error ? error.message : "Card extraction failed.");
            }

            if (response?.cards && !signal.aborted) {
                const { nodes: generatedNodes, idMap } = llmCardsToNodes(response.cards, dropPosition, {
                    createdAt: chosenCreatedAt,
                    origin: fileId,
                });
                const generatedNodeById = new Map(generatedNodes.map((node) => [node.id, node]));

                // Rebuilt per pass rather than snapshotted once: the similarity edges are queued
                // after an await, by which point the canvas has already gained the new cards.
                const buildEdgeQueuer = (target: edgeType[]) => {
                    const edgeKeyOf = (edge: edgeType) => {
                        const edgeLabel = typeof edge.label === "string"
                            ? edge.label
                            : (typeof edge.data?.label === "string" ? edge.data.label : "");
                        return `${edge.source}|${edge.target}|${edgeLabel}`;
                    };
                    const knownEdgeKeys = new Set(edgesRef.current.map(edgeKeyOf));

                    return (edge: edgeType) => {
                        const edgeKey = edgeKeyOf(edge);
                        if (knownEdgeKeys.has(edgeKey)) return;
                        knownEdgeKeys.add(edgeKey);
                        target.push({
                            ...edge,
                            data: {
                                ...(edge.data && typeof edge.data === "object" ? edge.data : {}),
                                createdAt: chosenCreatedAt,
                            },
                        });
                    };
                };

                const nodesToAdd: nodeType[] = [];
                const activityEdges: edgeType[] = [];
                const queueActivityEdge = buildEdgeQueuer(activityEdges);

                for (const card of response.cards) {
                    const targetNodeId = idMap[String(card.id)];
                    if (!targetNodeId || targetNodeId === rootActivityNodeId) continue;

                    const generatedNode = generatedNodeById.get(targetNodeId);
                    if (generatedNode) nodesToAdd.push(generatedNode);

                    const label = relationLabelFor("activity", normalizeArtifactEntity(card.entity));
                    if (label) {
                        queueActivityEdge({
                            id: crypto.randomUUID(),
                            source: rootActivityNodeId,
                            target: targetNodeId,
                            type: "relation",
                            label,
                            data: { label, from: "activity", to: normalizeArtifactEntity(card.entity) },
                        });
                    }
                }

                // Render as soon as the model answers. The similarity pass only ever adds
                // `iteration of` / `referenced by` edges between existing cards, so making the
                // cards wait for it bought nothing.
                if (nodesToAdd.length > 0) {
                    dispatch(addNodes(nodesToAdd));
                }
                if (activityEdges.length > 0) {
                    dispatch(connectEdges(activityEdges));
                }

                // `person` cards are excluded at the source rather than filtered out of the
                // verdicts: a name has no content to be similar *about*, so shipping one only
                // buys a retrieval round-trip whose every answer would be thrown away. See
                // `AUTO_LINK_EXCLUDED_LABELS`.
                const newCardsForSimilarity = nodesToAdd
                    .map((node) => {
                        const data = node.data as Record<string, unknown>;
                        return {
                            id: node.id,
                            label: normalizeArtifactEntity(String(data.label ?? "")),
                            title: typeof data.title === "string" ? data.title : "",
                            description: typeof data.description === "string" ? data.description : "",
                        };
                    })
                    .filter((card) => canAutoLink(card.label));

                if (newCardsForSimilarity.length > 0) {
                    void (async () => {
                        try {
                            // Only the new cards travel: the server holds the canvas and searches
                            // its own vector index.
                            const similarity = await compareCardsSimilarity(projectId, {
                                newCards: newCardsForSimilarity,
                            }, signal);
                            if (signal.aborted) return;

                            if (similarity.status !== "ok") {
                                console.warn(
                                    `Similarity lookup unavailable (${similarity.status}); no automatic relations were added.`,
                                );
                                return;
                            }

                            const relationEdges: edgeType[] = [];
                            const queueRelationEdge = buildEdgeQueuer(relationEdges);

                            // Degree is counted against the live graph *plus* what this pass has
                            // already queued, so one extraction cannot pile six edges onto the same
                            // card by never noticing its own work.
                            const autoDegree = countAutoLinkDegree(edgesRef.current);
                            const evidenceOf = (cardId: string): IterationEvidence | null => {
                                const node = generatedNodeById.get(cardId)
                                    ?? nodesRef.current.find((candidate) => candidate.id === cardId);
                                if (!node) return null;
                                const data = (node.data ?? {}) as Record<string, unknown>;
                                const createdAt = typeof data.createdAt === "string" ? Date.parse(data.createdAt) : NaN;
                                return {
                                    title: typeof data.title === "string" ? data.title : "",
                                    createdAtMs: Number.isFinite(createdAt) ? createdAt : null,
                                };
                            };

                            /**
                             * The far end of the edge is filtered *before* the gates run, not
                             * after. A `person` candidate left in the ranking would still consume
                             * one of the two edges a new card may take, and would still set the
                             * separation floor the real matches have to clear — so dropping its
                             * verdict afterwards would silently weaken the decision for every
                             * other candidate. Unknown ids are kept: the retrieval index can lag
                             * the live canvas, and "not found" is not evidence of a person.
                             */
                            const isAutoLinkableCard = (cardId: string): boolean => {
                                const node = generatedNodeById.get(cardId)
                                    ?? nodesRef.current.find((candidate) => candidate.id === cardId);
                                if (!node) return true;
                                return canAutoLink(String((node.data as Record<string, unknown>)?.label ?? ""));
                            };

                            for (const rawMatch of similarity.matches) {
                                const match = {
                                    ...rawMatch,
                                    candidates: rawMatch.candidates.filter(
                                        (candidate) => isAutoLinkableCard(candidate.existingCardId),
                                    ),
                                };
                                const verdicts = decideSimilarityEdges(match, {
                                    evidenceOf,
                                    autoDegreeOf: (cardId) => autoDegree.get(cardId) ?? 0,
                                });

                                if (DEBUG_SIMILARITY_SCORES) {
                                    console.log("[similarity]", {
                                        newCardId: match.newCardId,
                                        baseline: match.baseline,
                                        candidates: rawMatch.candidates,
                                        eligibleCandidates: match.candidates,
                                        accepted: verdicts,
                                        tuning: SIMILARITY_TUNING,
                                    });
                                }

                                for (const verdict of verdicts) {
                                    const generatedNode = generatedNodeById.get(match.newCardId);
                                    const normalizedEntity = normalizeArtifactEntity(
                                        String((generatedNode?.data as Record<string, unknown> | undefined)?.label ?? ""),
                                    );
                                    const existingNode = nodesRef.current.find((node) => node.id === verdict.existingCardId);
                                    const existingLabel = normalizeArtifactEntity(
                                        String((existingNode?.data as Record<string, unknown> | undefined)?.label ?? normalizedEntity),
                                    );
                                    const label = verdict.kind === "iteration_of"
                                        ? ITERATION_OF_LABEL
                                        : REFERENCED_BY_LABEL;

                                    queueRelationEdge({
                                        id: crypto.randomUUID(),
                                        source: match.newCardId,
                                        target: verdict.existingCardId,
                                        type: "relation",
                                        label,
                                        data: {
                                            label,
                                            from: normalizedEntity,
                                            to: existingLabel,
                                            kind: verdict.kind,
                                            // Kept on the edge so a questionable relation can be
                                            // explained after the fact, and so thresholds can be
                                            // retuned against real projects rather than guessed at.
                                            autoLinked: true,
                                            similarity: verdict.similarity,
                                            similarityZ: verdict.z,
                                            similarityMargin: verdict.margin,
                                        },
                                    });
                                    autoDegree.set(
                                        verdict.existingCardId,
                                        (autoDegree.get(verdict.existingCardId) ?? 0) + 1,
                                    );
                                }
                            }

                            if (relationEdges.length > 0 && !signal.aborted) {
                                dispatch(connectEdges(relationEdges));
                            }
                        } catch (error) {
                            if (signal.aborted) return;
                            console.error("Failed to compare generated cards with existing cards.", error);
                        }
                    })();
                }
            }
        } catch (error) {
            if (signal.aborted) return;
            console.error("Failed to process the attached file.", error);
            onExtractionError?.(error instanceof Error ? error.message : "Failed to process the attached file.");
        } finally {
            inFlightRef.current.delete(controller);
            setLoading(false);
        }
    }, [dispatch, onExtractionError, projectId, projectSettings, resolveActionTimestamp, setLoading]);

    const onAttachFile = useCallback(async (nodeId: string, file: File) => {
        const targetNode = nodesRef.current.find((node) => node.id === nodeId);
        const isActivityNode = String(targetNode?.data?.label ?? "").toLowerCase() === "activity";
        const shouldUseLlmFlow = isActivityNode && Boolean(targetNode) && !isVideoFile(file);

        if (shouldUseLlmFlow && targetNode) {
            await processFile(
                file,
                nodeId,
                { x: targetNode.position.x, y: targetNode.position.y },
            );
            return;
        }

        const parsedFile = await parseFile(file);
        const chosenCreatedAt = resolveActionTimestamp();
        const uploaded = await createFile(projectId, parsedFile, chosenCreatedAt);
        const {
            fileId,
            createdAt: persistedCreatedAt,
            sha256,
            bucket,
            key,
        } = uploaded;
        const parsedPersistedCreatedAt = new Date(persistedCreatedAt);
        const resolvedCreatedAt = Number.isNaN(parsedPersistedCreatedAt.getTime())
            ? chosenCreatedAt
            : parsedPersistedCreatedAt.toISOString();
        const { name, mimeType, sizeBytes, ext } = parsedFile;

        dispatch(upsertFile({
            id: fileId,
            docId: projectId,
            name,
            mimeType,
            sizeBytes,
            ext,
            createdAt: resolvedCreatedAt,
            sha256,
            storage: { bucket, key },
        }));
        dispatch(attachFileIdToNode({
            nodeId,
            fileId,
            editAt: chosenCreatedAt,
        }));
    }, [dispatch, processFile, projectId, resolveActionTimestamp]);

    /**
     * Canvas file drop. Always produces an `object` card named after the file, with the file
     * attached — no LLM round-trip, so the card appears as soon as the upload returns. When
     * `targetActivityNodeId` is set (the file was dropped inside an activity's drop ring) the
     * card is connected to that activity.
     *
     * `connection` overrides the relation that edge carries. Left out, it is the default for the
     * pair (`generated by`); the drop-ring flow asks the user once and passes the same answer for
     * every file in the drop, so a batch of files lands as one consistent set of relations.
     *
     * Returns the created card's id so the caller can bring it into view — the canvas layout, not
     * the drop point, decides where it actually lands.
     */
    const onAttachFileToCanvas = useCallback(async (
        file: File,
        dropPosition: { x: number; y: number },
        targetActivityNodeId?: string | null,
        connection?: CanvasDropConnection | null,
    ): Promise<string | null> => {
        setLoading(true);

        try {
            // No LLM consumes the preview text on this path, so skip reading the file contents.
            const parsedFile = await parseFile(file, { includePreviewText: false });
            const { name, mimeType, sizeBytes, ext } = parsedFile;
            const chosenCreatedAt = resolveActionTimestamp();
            const uploaded = await createFile(projectId, parsedFile, chosenCreatedAt);
            const {
                fileId,
                createdAt: persistedCreatedAt,
                sha256,
                bucket,
                key,
            } = uploaded;
            const parsedPersistedCreatedAt = new Date(persistedCreatedAt);
            const resolvedCreatedAt = Number.isNaN(parsedPersistedCreatedAt.getTime())
                ? chosenCreatedAt
                : parsedPersistedCreatedAt.toISOString();

            dispatch(upsertFile({
                id: fileId,
                docId: projectId,
                name,
                mimeType,
                sizeBytes,
                ext,
                createdAt: resolvedCreatedAt,
                sha256,
                storage: { bucket, key },
            }));

            const activityNodeId = typeof targetActivityNodeId === "string" && targetActivityNodeId.trim() !== ""
                ? targetActivityNodeId
                : null;
            const activityNode = activityNodeId
                ? nodesRef.current.find((node) => node.id === activityNodeId)
                : undefined;

            const nodeId = crypto.randomUUID();
            dispatch(addNode({
                id: nodeId,
                // Recorded as the drop point; the orbit layout decides where the card renders.
                position: dropPosition,
                type: "card",
                data: {
                    label: "object",
                    type: typeFromLabel("object"),
                    title: titleFromFilename(parsedFile.name),
                    description: "",
                    createdAt: chosenCreatedAt,
                    origin: fileId,
                    // Deliberately **not** `autoGenerated`. This path never calls the model
                    // (contract 14) — the user dragged the file in and the title is its filename —
                    // and the flag is what marks a card as model-derived on the canvas and what the
                    // provenance filter hides. Marking a hand-made card here would make both lie.
                    // `origin` still points at the file, so the back of the card keeps citing it.
                    relevant: true,
                    attachmentIds: [fileId],
                },
            }));

            dispatch(attachFileIdToNode({
                nodeId,
                fileId,
                editAt: chosenCreatedAt,
            }));

            if (activityNode) {
                const relationLabel = connection?.label?.trim() || relationLabelFor("activity", "object");
                if (relationLabel) {
                    dispatch(connectEdges([{
                        id: crypto.randomUUID(),
                        source: activityNode.id,
                        target: nodeId,
                        type: "relation",
                        label: relationLabel,
                        data: {
                            label: relationLabel,
                            from: "activity",
                            to: "object",
                            createdAt: chosenCreatedAt,
                            ...(connection?.kind ? { kind: connection.kind } : {}),
                        },
                    }]));
                }
            }

            return nodeId;
        } finally {
            setLoading(false);
        }
    }, [dispatch, projectId, resolveActionTimestamp, setLoading]);

    return {
        onAttachFile,
        onAttachFileToCanvas,
    };
}
