import { useCallback, useEffect, useRef } from "react";

import { parseFile } from "@/func/FileParser";
import { llmCardsToNodes, requestCardsLLM } from "@/func/LLMRequest";
import type { LlmProjectSettingsContext } from "@/func/LLMRequest";
import { createFile } from "@/api/stateApi";
import { autoLinkNewCards } from "@/pages/projectEditor/autoLinkCards";
import {
    normalizeArtifactEntity,
    nodeLabelOf,
    type ConnectionKind,
} from "@/pages/projectEditor/graphSemantics";
import { addNode, attachFileIdToNode, addNodes, connectEdges } from "@/store/flowSlice";
import { upsertFile } from "@/store/filesSlice";
import { relationLabelFor } from "@/utils/relationships";
import { cardTypeForLabel } from "@/components/cards/cardVisuals";

import type { AppDispatch } from "@/store";
import type { edgeType, filePendingUpload, llmCardData, llmConnectionData, nodeType } from "@/config/types";

type Args = {
    projectId: string;
    dispatch: AppDispatch;
    nodes: nodeType[];
    edges: edgeType[];
    projectSettings: LlmProjectSettingsContext;
    actionTimestamp?: string | null;
    setLoading: (value: boolean) => void;
    /** Surfaced to the user in place of the old blocking `alert`. */
    onExtractionError?: (message: string) => void;
};

/**
 * The relation a dropped file's card gets to the card it landed on. Chosen once per drop and
 * applied to every file in it, so a batch never ends up half `generated by` and half something else.
 */
export type CanvasDropConnection = {
    label: string;
    /** Set for the two semantic relations; left out for the pair's own default label. */
    kind?: Exclude<ConnectionKind, "regular">;
};

/**
 * The card a drop attaches to: an activity whose ring the file landed in, or any card whose spawn
 * box it landed on. `direction` is the side of that card the box sits on — `outgoing` puts the
 * anchor on the edge's source, which is what the activity-ring drop has always done.
 */
export type CanvasDropAnchor = {
    nodeId: string;
    direction: "incoming" | "outgoing";
};

const VIDEO_EXTENSIONS = new Set(["mp4", "webm", "mov", "m4v", "ogg", "ogv", "avi"]);

function titleFromFilename(filename: string): string {
    const withoutExt = filename.replace(/\.[^/.]+$/, "").trim();
    return withoutExt || "Untitled";
}

function extensionFromName(filename: string): string {
    if (!filename.includes(".")) return "";
    return filename.split(".").pop()?.toLowerCase() ?? "";
}

function isVideoMimeType(mimeType: string | undefined): boolean {
    return typeof mimeType === "string" && mimeType.toLowerCase().startsWith("video/");
}

function isVideoFile(file: File): boolean {
    return isVideoMimeType(file.type) || VIDEO_EXTENSIONS.has(extensionFromName(file.name));
}

function isVideoPendingUpload(file: filePendingUpload): boolean {
    return isVideoMimeType(file.mimeType) || VIDEO_EXTENSIONS.has(String(file.ext ?? "").toLowerCase());
}

export function useFileAttachmentProcessing({
    projectId,
    dispatch,
    nodes,
    edges,
    projectSettings,
    actionTimestamp = null,
    setLoading,
    onExtractionError,
}: Args) {
    const nodesRef = useRef(nodes);
    const edgesRef = useRef(edges);
    // Every in-flight drop, so switching projects mid-drop cannot let an upload or extraction
    // dispatch its results into a different document's store. Concurrent drops are kept
    // independent: starting one must never cancel another that is still running.
    const inFlightRef = useRef<Set<AbortController>>(new Set());

    useEffect(() => {
        nodesRef.current = nodes;
    }, [nodes]);

    useEffect(() => {
        edgesRef.current = edges;
    }, [edges]);

    useEffect(() => {
        const controllers = inFlightRef.current;
        return () => {
            for (const controller of controllers) controller.abort();
            controllers.clear();
        };
    }, [projectId]);

    const resolveActionTimestamp = useCallback(() => {
        if (actionTimestamp) {
            const parsed = new Date(actionTimestamp);
            if (!Number.isNaN(parsed.getTime())) return parsed.toISOString();
        }
        return new Date().toISOString();
    }, [actionTimestamp]);

    /**
     * Attach a file to an activity card and let the LLM turn it into cards.
     *
     * The file's timestamp is the current timeline action timestamp — there is no prompt for it.
     * An activity's own timestamp is editable on the back of its card, which is the one place that
     * decides where the tree sits on the time axis, so asking again per file was a modal in the way
     * of every attachment.
     */
    const processFile = useCallback(async (
        file: File,
        rootActivityNodeId: string,
        dropPosition?: { x: number; y: number },
    ) => {
        setLoading(true);
        const controller = new AbortController();
        inFlightRef.current.add(controller);
        const { signal } = controller;

        try {
            const data: filePendingUpload = await parseFile(file);
            const chosenCreatedAt = resolveActionTimestamp();

            // The extraction call needs only the parsed file, never the upload result, so the two
            // run concurrently. For pdf/docx this also overlaps the docling conversion with the
            // upload, since that round trip happens inside requestCardsLLM.
            const isVideo = isVideoPendingUpload(data);
            const uploadPromise = createFile(projectId, data, chosenCreatedAt, signal);
            const llmPromise = isVideo ? null : requestCardsLLM(data, projectSettings, signal);
            // Attached up front so a failure on one leg is never an unhandled rejection while the
            // other is still in flight.
            uploadPromise.catch(() => { });
            llmPromise?.catch(() => { });

            const uploaded = await uploadPromise;
            const {
                fileId,
                createdAt: persistedCreatedAt,
                sha256,
                bucket,
                key,
            } = uploaded;
            const parsedPersistedCreatedAt = new Date(persistedCreatedAt);
            const resolvedCreatedAt = Number.isNaN(parsedPersistedCreatedAt.getTime())
                ? chosenCreatedAt
                : parsedPersistedCreatedAt.toISOString();
            const { name, mimeType, sizeBytes, ext } = data;

            dispatch(upsertFile({
                id: fileId,
                docId: projectId,
                name,
                mimeType,
                sizeBytes,
                ext,
                createdAt: resolvedCreatedAt,
                sha256,
                storage: { bucket, key },
            }));

            // Attach as soon as upload metadata is available, independent of LLM success.
            dispatch(attachFileIdToNode({
                nodeId: rootActivityNodeId,
                fileId,
                editAt: chosenCreatedAt,
            }));

            if (!llmPromise) {
                return;
            }

            let response: { cards: llmCardData[]; connections: llmConnectionData[] } | null = null;
            try {
                response = await llmPromise;
            } catch (error) {
                if (signal.aborted) return;
                console.error("LLM processing failed for attached file.", error);
                onExtractionError?.(error instanceof Error ? error.message : "Card extraction failed.");
            }

            if (response?.cards && !signal.aborted) {
                const { nodes: generatedNodes, idMap } = llmCardsToNodes(response.cards, dropPosition, {
                    createdAt: chosenCreatedAt,
                    origin: fileId,
                });
                const generatedNodeById = new Map(generatedNodes.map((node) => [node.id, node]));

                // Rebuilt per pass rather than snapshotted once: the similarity edges are queued
                // after an await, by which point the canvas has already gained the new cards.
                const buildEdgeQueuer = (target: edgeType[]) => {
                    const edgeKeyOf = (edge: edgeType) => {
                        const edgeLabel = typeof edge.label === "string"
                            ? edge.label
                            : (typeof edge.data?.label === "string" ? edge.data.label : "");
                        return `${edge.source}|${edge.target}|${edgeLabel}`;
                    };
                    const knownEdgeKeys = new Set(edgesRef.current.map(edgeKeyOf));

                    return (edge: edgeType) => {
                        const edgeKey = edgeKeyOf(edge);
                        if (knownEdgeKeys.has(edgeKey)) return;
                        knownEdgeKeys.add(edgeKey);
                        target.push({
                            ...edge,
                            data: {
                                ...(edge.data && typeof edge.data === "object" ? edge.data : {}),
                                createdAt: chosenCreatedAt,
                            },
                        });
                    };
                };

                const nodesToAdd: nodeType[] = [];
                const activityEdges: edgeType[] = [];
                const queueActivityEdge = buildEdgeQueuer(activityEdges);

                for (const card of response.cards) {
                    const targetNodeId = idMap[String(card.id)];
                    if (!targetNodeId || targetNodeId === rootActivityNodeId) continue;

                    const generatedNode = generatedNodeById.get(targetNodeId);
                    if (generatedNode) nodesToAdd.push(generatedNode);

                    const label = relationLabelFor("activity", normalizeArtifactEntity(card.entity));
                    if (label) {
                        queueActivityEdge({
                            id: crypto.randomUUID(),
                            source: rootActivityNodeId,
                            target: targetNodeId,
                            type: "relation",
                            label,
                            // This card exists because the model proposed it, so the edge that
                            // attaches it is the model's too — nobody drew it. Marked like the
                            // card and like the model's own card-to-card connections.
                            data: {
                                label,
                                from: "activity",
                                to: normalizeArtifactEntity(card.entity),
                                autoGenerated: true,
                            },
                        });
                    }
                }

                // Render as soon as the model answers. The similarity pass only ever adds
                // `iteration of` / `referenced by` edges between existing cards, so making the
                // cards wait for it bought nothing.
                if (nodesToAdd.length > 0) {
                    dispatch(addNodes(nodesToAdd));
                }
                if (activityEdges.length > 0) {
                    dispatch(connectEdges(activityEdges));
                }

                // Offered to the rest of the canvas through the shared pass, which the note tool
                // uses too -- extraction and authorship get the same evidence gates.
                void autoLinkNewCards({
                    projectId,
                    newNodes: nodesToAdd,
                    nodesRef,
                    edgesRef,
                    dispatch,
                    createdAt: chosenCreatedAt,
                    signal,
                });
            }
        } catch (error) {
            if (signal.aborted) return;
            console.error("Failed to process the attached file.", error);
            onExtractionError?.(error instanceof Error ? error.message : "Failed to process the attached file.");
        } finally {
            inFlightRef.current.delete(controller);
            setLoading(false);
        }
    }, [dispatch, onExtractionError, projectId, projectSettings, resolveActionTimestamp, setLoading]);

    const onAttachFile = useCallback(async (nodeId: string, file: File) => {
        const targetNode = nodesRef.current.find((node) => node.id === nodeId);
        const isActivityNode = String(targetNode?.data?.label ?? "").toLowerCase() === "activity";
        const shouldUseLlmFlow = isActivityNode && Boolean(targetNode) && !isVideoFile(file);

        if (shouldUseLlmFlow && targetNode) {
            await processFile(
                file,
                nodeId,
                { x: targetNode.position.x, y: targetNode.position.y },
            );
            return;
        }

        const parsedFile = await parseFile(file);
        const chosenCreatedAt = resolveActionTimestamp();
        const uploaded = await createFile(projectId, parsedFile, chosenCreatedAt);
        const {
            fileId,
            createdAt: persistedCreatedAt,
            sha256,
            bucket,
            key,
        } = uploaded;
        const parsedPersistedCreatedAt = new Date(persistedCreatedAt);
        const resolvedCreatedAt = Number.isNaN(parsedPersistedCreatedAt.getTime())
            ? chosenCreatedAt
            : parsedPersistedCreatedAt.toISOString();
        const { name, mimeType, sizeBytes, ext } = parsedFile;

        dispatch(upsertFile({
            id: fileId,
            docId: projectId,
            name,
            mimeType,
            sizeBytes,
            ext,
            createdAt: resolvedCreatedAt,
            sha256,
            storage: { bucket, key },
        }));
        dispatch(attachFileIdToNode({
            nodeId,
            fileId,
            editAt: chosenCreatedAt,
        }));
    }, [dispatch, processFile, projectId, resolveActionTimestamp]);

    /**
     * Canvas file drop. Always produces an `object` card named after the file, with the file
     * attached — no LLM round-trip, so the card appears as soon as the upload returns. When
     * `anchor` is set (the file was dropped inside an activity's drop ring, or on a card's spawn
     * box) the card is connected to that card.
     *
     * `connection` overrides the relation that edge carries. Left out, it is the default for the
     * pair (`generated by`); the drop-ring flow asks the user once and passes the same answer for
     * every file in the drop, so a batch of files lands as one consistent set of relations.
     *
     * Returns the created card's id so the caller can bring it into view — the canvas layout, not
     * the drop point, decides where it actually lands.
     */
    const onAttachFileToCanvas = useCallback(async (
        file: File,
        dropPosition: { x: number; y: number },
        anchor?: CanvasDropAnchor | null,
        connection?: CanvasDropConnection | null,
    ): Promise<string | null> => {
        setLoading(true);

        try {
            // No LLM consumes the preview text on this path, so skip reading the file contents.
            const parsedFile = await parseFile(file, { includePreviewText: false });
            const { name, mimeType, sizeBytes, ext } = parsedFile;
            const chosenCreatedAt = resolveActionTimestamp();
            const uploaded = await createFile(projectId, parsedFile, chosenCreatedAt);
            const {
                fileId,
                createdAt: persistedCreatedAt,
                sha256,
                bucket,
                key,
            } = uploaded;
            const parsedPersistedCreatedAt = new Date(persistedCreatedAt);
            const resolvedCreatedAt = Number.isNaN(parsedPersistedCreatedAt.getTime())
                ? chosenCreatedAt
                : parsedPersistedCreatedAt.toISOString();

            dispatch(upsertFile({
                id: fileId,
                docId: projectId,
                name,
                mimeType,
                sizeBytes,
                ext,
                createdAt: resolvedCreatedAt,
                sha256,
                storage: { bucket, key },
            }));

            const anchorNodeId = typeof anchor?.nodeId === "string" && anchor.nodeId.trim() !== ""
                ? anchor.nodeId
                : null;
            const anchorNode = anchorNodeId
                ? nodesRef.current.find((node) => node.id === anchorNodeId)
                : undefined;

            const nodeId = crypto.randomUUID();
            dispatch(addNode({
                id: nodeId,
                // Recorded as the drop point; the orbit layout decides where the card renders.
                position: dropPosition,
                type: "card",
                data: {
                    label: "object",
                    type: cardTypeForLabel("object"),
                    title: titleFromFilename(parsedFile.name),
                    description: "",
                    createdAt: chosenCreatedAt,
                    origin: fileId,
                    // Deliberately **not** `autoGenerated`. This path never calls the model
                    // (contract 14) — the user dragged the file in and the title is its filename —
                    // and the flag is what marks a card as model-derived on the canvas and what the
                    // provenance filter hides. Marking a hand-made card here would make both lie.
                    // `origin` still points at the file, so the back of the card keeps citing it.
                    relevant: true,
                    attachmentIds: [fileId],
                },
            }));

            dispatch(attachFileIdToNode({
                nodeId,
                fileId,
                editAt: chosenCreatedAt,
            }));

            if (anchorNode) {
                const anchorLabel = nodeLabelOf(anchorNode);
                const relationLabel = connection?.label?.trim() || relationLabelFor(anchorLabel, "object");
                if (relationLabel) {
                    // `outgoing` means the box sat on the anchor's source handle, so the anchor is
                    // the edge's source — which is also what the activity ring has always produced.
                    const anchorIsSource = anchor?.direction !== "incoming";
                    dispatch(connectEdges([{
                        id: crypto.randomUUID(),
                        source: anchorIsSource ? anchorNode.id : nodeId,
                        target: anchorIsSource ? nodeId : anchorNode.id,
                        type: "relation",
                        label: relationLabel,
                        data: {
                            label: relationLabel,
                            from: anchorIsSource ? anchorLabel : "object",
                            to: anchorIsSource ? "object" : anchorLabel,
                            createdAt: chosenCreatedAt,
                            ...(connection?.kind ? { kind: connection.kind } : {}),
                        },
                    }]));
                }
            }

            return nodeId;
        } finally {
            setLoading(false);
        }
    }, [dispatch, projectId, resolveActionTimestamp, setLoading]);

    return {
        onAttachFile,
        onAttachFileToCanvas,
    };
}
