/**
 * Did a model put this relation on the canvas, or did a person draw it?
 *
 * Two markers answer to the same fact, written by two different machines:
 *
 * - `autoGenerated` — the extraction pass. Set on the cards an LLM proposes (`llmCardsToNodes`) and
 *   on the edges drawn to attach them, so a card and the relation that justifies it agree.
 * - `autoLinked` — the similarity pass (`autoLinkCards`). Server-side embeddings decide which
 *   existing card a new one is an `iteration of` or is `referenced by`, and the score that carried
 *   the decision is kept beside the flag. Different mechanism, same answer to the only question the
 *   reader is asking: nobody drew this.
 *
 * A hand-drawn edge carries `manual: true` instead — but only since that flag was added, so its
 * absence is never evidence of anything. Nothing here infers provenance from a missing marker.
 */
export function isModelDerivedEdgeData(data: unknown): boolean {
    if (!data || typeof data !== "object") return false;
    const record = data as Record<string, unknown>;
    return record.autoGenerated === true || record.autoLinked === true;
}

/**
 * The same question about a **node**: did a model propose this card, or did a person put it there?
 *
 * One marker, not two: only the extraction pass writes `autoGenerated` on a node
 * (`llmCardsToNodes`, and the edge half in `useFileAttachmentProcessing`). It is deliberately *not*
 * set on the card a dropped file becomes — a person dragged that file in, so the flag means
 * *machine-proposed*, never *machine-touched*. That distinction is the whole reason
 * `SALIENCE_WEIGHTS.authored` is a defensible term rather than a guess.
 *
 * It sits beside its edge twin because the two are asked together everywhere they are asked at all —
 * the sidebar's provenance chips, the card's own badge, the salience scalar, and the exported
 * report's authorship tally. Three inline copies of this line existed before this function did, and
 * a fourth in the report would have made "which cards are the researcher's own work" a question the
 * codebase answered in four places.
 */
export function isModelDerivedNodeData(data: unknown): boolean {
    if (!data || typeof data !== "object") return false;
    return (data as Record<string, unknown>).autoGenerated === true;
}
