/**
 * Did a model put this relation on the canvas, or did a person draw it?
 *
 * Two markers answer to the same fact, written by two different machines:
 *
 * - `autoGenerated` — the extraction pass. Set on the cards an LLM proposes (`llmCardsToNodes`) and
 *   on the edges drawn to attach them, so a card and the relation that justifies it agree.
 * - `autoLinked` — the similarity pass (`autoLinkCards`). Server-side embeddings decide which
 *   existing card a new one is an `iteration of` or is `referenced by`, and the score that carried
 *   the decision is kept beside the flag. Different mechanism, same answer to the only question the
 *   reader is asking: nobody drew this.
 *
 * A hand-drawn edge carries `manual: true` instead — but only since that flag was added, so its
 * absence is never evidence of anything. Nothing here infers provenance from a missing marker.
 */
export function isModelDerivedEdgeData(data: unknown): boolean {
    if (!data || typeof data !== "object") return false;
    const record = data as Record<string, unknown>;
    return record.autoGenerated === true || record.autoLinked === true;
}
