const ALLOWED_RELATION_LABEL_BY_PAIR: Record<string, string> = {
    "activity|person": "part of",
    "activity|activity": "related to",
    "activity|requirement": "derived from",
    "activity|concept": "relevant to",
    "activity|insight": "derived from",
    "activity|object": "generated by",
    "requirement|requirement": "details",
    "concept|insight": "part of",
    "concept|concept": "composes",
    "object|object": "relevant to",
    "object|requirement": "tackles",
    "activity|task": "derived from",
    "object|task": "relevant to"
};

export function relationPairKey(a: string, b: string): string {
    return [a.toLowerCase(), b.toLowerCase()].sort().join("|");
}

export function relationLabelFor(a: string, b: string): string | undefined {
    return ALLOWED_RELATION_LABEL_BY_PAIR[relationPairKey(a, b)];
}

export function isAllowedConnection(a?: string, b?: string): boolean {
    if (!a || !b) return false;
    return !!relationLabelFor(a, b);
}